name: Build and Deploy Storybook
permissions:
  contents: write
on:
  push:
    branches:
      - main
    paths: ['src/stories/**', 'src/lib/**']
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm ci
          npm run build-storybook

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static
          clean: true
